version: '3.8'
services:
  postgres:
    image: postgres:17-alpine
    container_name: e-commerce-db
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: e-commerce
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - '3000:3000'

volumes:
  pgdata:
